version: 0.2

phases:
  pre_build:
    commands:
      - export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain airtext-pypi --domain-owner 312590578399 --query authorizationToken --output text`
      - export PIP_INDEX_URL=https://aws:$CODEARTIFACT_AUTH_TOKEN@airtext-pypi-312590578399.d.codeartifact.us-east-1.amazonaws.com/pypi/airtext-pypi-store/simple/
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 312590578399.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - docker build --no-cache --build-arg PIP_INDEX_URL=$PIP_INDEX_URL -t prod-airtext-api-contacts-put-lambda airtext_api/contacts/delete/.
      - docker tag prod-airtext-api-contacts-put-lambda:latest 312590578399.dkr.ecr.us-east-1.amazonaws.com/prod-airtext-api-contacts-put-lambda:latest
      - docker push 312590578399.dkr.ecr.us-east-1.amazonaws.com/prod-airtext-api-contacts-put-lambda:latest
  post_build:
    commands:
      - aws lambda update-function-code --function-name prod-airtext-api-contacts-put --image-uri 312590578399.dkr.ecr.us-east-1.amazonaws.com/prod-airtext-api-contacts-put-lambda:latest
