"""unique constraints on number and member_id in contacts

Revision ID: 094538708c2d
Revises: 2276946b4396
Create Date: 2022-08-16 14:07:17.621426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "094538708c2d"
down_revision = "2276946b4396"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cmda_exec")
    op.create_unique_constraint(None, "contacts", ["number", "member_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contacts", type_="unique")
    op.create_table(
        "cmda_exec",
        sa.Column("cmda_output", sa.TEXT(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
