"""number names column add integer new

Revision ID: 0b1988a0a8d4
Revises: 4c5efea9e201
Create Date: 2022-09-08 05:48:37.783286

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1988a0a8d4'
down_revision = '4c5efea9e201'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
