"""updated columns structure, removed redundancy

Revision ID: 0cbcb0df8f21
Revises: 2cab1481f7db
Create Date: 2022-08-12 02:53:55.176388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0cbcb0df8f21"
down_revision = "2cab1481f7db"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "compaign_contacts", sa.Column("campaign_id", sa.INTEGER(), nullable=True)
    )
    op.drop_constraint(
        "compaign_contacts_member_id_fkey", "compaign_contacts", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "compaign_contacts", "campaigns", ["campaign_id"], ["id"]
    )
    op.drop_column("compaign_contacts", "member_id")
    op.drop_column("contacts", "name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "contacts",
        sa.Column("name", sa.VARCHAR(length=36), autoincrement=False, nullable=True),
    )
    op.add_column(
        "compaign_contacts",
        sa.Column("member_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "compaign_contacts", type_="foreignkey")
    op.create_foreign_key(
        "compaign_contacts_member_id_fkey",
        "compaign_contacts",
        "members",
        ["member_id"],
        ["id"],
    )
    op.drop_column("compaign_contacts", "campaign_id")
    # ### end Alembic commands ###
