"""number names column

Revision ID: 118c35db1b0d
Revises: 4069100815d6
Create Date: 2022-09-08 05:33:42.205675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118c35db1b0d'
down_revision = '4069100815d6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
