"""Adding relationships

Revision ID: 179f789724ba
Revises: bc80a9ff7371
Create Date: 2022-09-06 05:08:57.081668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '179f789724ba'
down_revision = 'bc80a9ff7371'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
