"""Adding on delete cascade

Revision ID: 194d5ec7da65
Revises: 179f789724ba
Create Date: 2022-09-06 05:11:34.813851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194d5ec7da65'
down_revision = '179f789724ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
