"""revamping app db

Revision ID: 2565073f8627
Revises: 
Create Date: 2023-08-26 02:41:01.397933

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2565073f8627'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.VARCHAR(length=36), nullable=True),
    sa.Column('email', sa.VARCHAR(length=128), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=12), nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('contacts',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('member_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('number', sa.VARCHAR(length=12), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=36), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('groups',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('member_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('name', sa.VARCHAR(length=36), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('member_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('to_number', sa.VARCHAR(length=12), nullable=False),
    sa.Column('from_number', sa.VARCHAR(length=12), nullable=False),
    sa.Column('body', sa.VARCHAR(length=720), nullable=True),
    sa.Column('media_url', sa.VARCHAR(length=720), nullable=True),
    sa.Column('twilio_message_sid', sa.VARCHAR(length=128), nullable=False),
    sa.Column('twilio_uri', sa.VARCHAR(length=128), nullable=False),
    sa.Column('twilio_error_code', sa.VARCHAR(length=128), nullable=True),
    sa.Column('twilio_error_message', sa.VARCHAR(length=128), nullable=True),
    sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_contacts',
    sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('contact_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('group_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.Column('created_on', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('contact_id', 'group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_contacts')
    op.drop_table('messages')
    op.drop_table('groups')
    op.drop_table('contacts')
    op.drop_table('members')
    # ### end Alembic commands ###
