"""number names column add

Revision ID: 268a30e2bfe2
Revises: cfd14f4abf4b
Create Date: 2022-09-08 05:36:22.197599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268a30e2bfe2'
down_revision = 'cfd14f4abf4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
