"""number names column

Revision ID: 3cf54c1b6ece
Revises: d3bd5548ce4c
Create Date: 2022-09-08 05:32:14.937599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cf54c1b6ece'
down_revision = 'd3bd5548ce4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
