"""number names column

Revision ID: 4069100815d6
Revises: d12582287774
Create Date: 2022-09-08 05:33:28.551736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4069100815d6'
down_revision = 'd12582287774'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
