"""fixing nullables

Revision ID: 44deaa847e9e
Revises: 66981024849d
Create Date: 2022-09-08 02:08:42.281242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44deaa847e9e'
down_revision = '66981024849d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
