"""number names column adddd

Revision ID: 4a688b258266
Revises: 268a30e2bfe2
Create Date: 2022-09-08 05:36:31.524638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a688b258266'
down_revision = '268a30e2bfe2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
