"""number names column add integer new

Revision ID: 4c5efea9e201
Revises: 7a777aec365e
Create Date: 2022-09-08 05:41:35.134350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5efea9e201'
down_revision = '7a777aec365e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('number_names', sa.INTEGER(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'number_names')
    # ### end Alembic commands ###
