"""add name field to contacts

Revision ID: 4ce7dd4ba5e6
Revises: e3ea7fedaa2f
Create Date: 2022-08-12 11:29:53.836859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ce7dd4ba5e6'
down_revision = 'e3ea7fedaa2f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('name', sa.VARCHAR(length=36), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contacts', 'name')
    # ### end Alembic commands ###
