"""messages from_number to to_number

Revision ID: 58a48011cf4b
Revises: efc8c5e86fd7
Create Date: 2022-08-18 06:23:31.265190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "58a48011cf4b"
down_revision = "efc8c5e86fd7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages", sa.Column("to_number", sa.VARCHAR(length=12), nullable=True)
    )
    op.drop_column("messages", "from_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages",
        sa.Column(
            "from_number", sa.VARCHAR(length=12), autoincrement=False, nullable=False
        ),
    )
    op.drop_column("messages", "to_number")
    # ### end Alembic commands ###
