"""added test table

Revision ID: 5a1c9e9f1b7c
Revises: 74e8f0f3589e
Create Date: 2022-08-13 12:23:04.757546

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5a1c9e9f1b7c"
down_revision = "74e8f0f3589e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("contacts")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.VARCHAR(length=36), autoincrement=False, nullable=True),
        sa.Column("member_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column("number", sa.VARCHAR(length=12), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"], ["members.id"], name="contacts_member_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="contacts_pkey"),
    )
    # ### end Alembic commands ###
