"""Nullable fields

Revision ID: 66981024849d
Revises: 8db850dd6e56
Create Date: 2022-09-07 15:22:39.811214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66981024849d'
down_revision = '8db850dd6e56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
