"""change proxy_number to 12 character

Revision ID: 70accf65f508
Revises: bcac4cd8a2c7
Create Date: 2022-08-12 15:59:44.117125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "70accf65f508"
down_revision = "bcac4cd8a2c7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
