"""phone numbers are not nullable

Revision ID: 74e8f0f3589e
Revises: cb738df19782
Create Date: 2022-08-13 00:46:56.316109

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "74e8f0f3589e"
down_revision = "cb738df19782"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contacts", "number", existing_type=sa.VARCHAR(length=12), nullable=False
    )
    op.alter_column(
        "members", "number", existing_type=sa.VARCHAR(length=12), nullable=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "members", "number", existing_type=sa.VARCHAR(length=12), nullable=True
    )
    op.alter_column(
        "contacts", "number", existing_type=sa.VARCHAR(length=12), nullable=True
    )
    # ### end Alembic commands ###
