"""Rename columns

Revision ID: 75b39db2ebd3
Revises: f5ff289926db
Create Date: 2022-09-08 06:26:32.342766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75b39db2ebd3'
down_revision = 'f5ff289926db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('media_url', sa.VARCHAR(length=720), nullable=True))
    op.drop_column('messages', 'media_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('media_content', sa.VARCHAR(length=720), autoincrement=False, nullable=True))
    op.drop_column('messages', 'media_url')
    # ### end Alembic commands ###
