"""unique constraint on contact name and member

Revision ID: 767c55a3726b
Revises: b707412216fc
Create Date: 2022-09-14 05:54:38.871803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '767c55a3726b'
down_revision = 'b707412216fc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'contacts', ['number', 'member_id'])
    op.create_unique_constraint(None, 'contacts', ['name', 'member_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='unique')
    op.drop_constraint(None, 'contacts', type_='unique')
    # ### end Alembic commands ###
