"""number names column

Revision ID: 81873d5014f7
Revises: 9371dacc9587
Create Date: 2022-09-08 05:35:18.790614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81873d5014f7'
down_revision = '9371dacc9587'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
