"""number names column add integer new

Revision ID: 838261f147a8
Revises: f9d8a117756f
Create Date: 2022-09-08 05:52:19.606790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '838261f147a8'
down_revision = 'f9d8a117756f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('number_names', postgresql.ARRAY(sa.VARCHAR(length=36)), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'number_names')
    # ### end Alembic commands ###
