"""Adding relationships

Revision ID: 8db850dd6e56
Revises: 18231c98ad52
Create Date: 2022-09-06 23:51:22.464643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8db850dd6e56'
down_revision = '18231c98ad52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
