"""fixing members table

Revision ID: 90f7470e6857
Revises: 2565073f8627
Create Date: 2023-08-26 02:57:45.219174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90f7470e6857'
down_revision = '2565073f8627'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('first_name', sa.VARCHAR(length=36), nullable=True))
    op.add_column('members', sa.Column('last_name', sa.VARCHAR(length=36), nullable=True))
    op.drop_column('members', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('name', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.drop_column('members', 'last_name')
    op.drop_column('members', 'first_name')
    # ### end Alembic commands ###
