"""number names column

Revision ID: 9371dacc9587
Revises: bf410860a9c4
Create Date: 2022-09-08 05:35:07.899633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9371dacc9587'
down_revision = 'bf410860a9c4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
