"""added message model

Revision ID: 9a592f400f08
Revises: 9c717f489e66
Create Date: 2022-08-16 17:41:59.279106

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9a592f400f08"
down_revision = "9c717f489e66"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("proxy_number", sa.VARCHAR(length=12), nullable=False),
        sa.Column("from_number", sa.VARCHAR(length=12), nullable=False),
        sa.Column("member_id", sa.INTEGER(), nullable=True),
        sa.Column("command", sa.VARCHAR(length=12), nullable=True),
        sa.Column("number", sa.VARCHAR(length=12), nullable=True),
        sa.Column("name", sa.VARCHAR(length=36), nullable=True),
        sa.Column("body", sa.VARCHAR(length=720), nullable=True),
        sa.Column("error", sa.BOOLEAN(), nullable=True),
        sa.Column("error_message", sa.VARCHAR(length=144), nullable=True),
        sa.Column(
            "created_on",
            postgresql.TIMESTAMP(),
            server_default=sa.text("CURRENT_TIMESTAMP"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["member_id"],
            ["members.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    # ### end Alembic commands ###
