"""added twilio columns to messages

Revision ID: a651022e0435
Revises: 75b39db2ebd3
Create Date: 2022-09-08 19:56:49.323884

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a651022e0435'
down_revision = '75b39db2ebd3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('twilio_uri', sa.VARCHAR(length=128), nullable=False))
    op.add_column('messages', sa.Column('twilio_error_code', sa.VARCHAR(length=128), nullable=True))
    op.add_column('messages', sa.Column('twilio_error_message', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'twilio_error_message')
    op.drop_column('messages', 'twilio_error_code')
    op.drop_column('messages', 'twilio_uri')
    # ### end Alembic commands ###
