"""number names column add integer new

Revision ID: b2162ee18c97
Revises: 0b1988a0a8d4
Create Date: 2022-09-08 05:48:51.618047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2162ee18c97'
down_revision = '0b1988a0a8d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
