"""tmp contacts

Revision ID: b42d287823e3
Revises: 40d2e1856ce0
Create Date: 2022-09-13 03:27:33.120810

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b42d287823e3'
down_revision = '40d2e1856ce0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('contacts_tmp', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.add_column('messages', sa.Column('groups_tmp', postgresql.JSON(astext_type=sa.Text()), nullable=True))
    op.drop_column('messages', 'groups')
    op.drop_column('messages', 'contacts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('contacts', postgresql.ARRAY(sa.VARCHAR(length=36)), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('groups', postgresql.ARRAY(sa.VARCHAR(length=36)), autoincrement=False, nullable=True))
    op.drop_column('messages', 'groups_tmp')
    op.drop_column('messages', 'contacts_tmp')
    # ### end Alembic commands ###
