"""unique constraint on contact name and member

Revision ID: b707412216fc
Revises: f99870f12a9d
Create Date: 2022-09-14 05:52:10.659586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b707412216fc'
down_revision = 'f99870f12a9d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_name_member_id_key', 'contacts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('contacts_name_member_id_key', 'contacts', ['name', 'member_id'])
    # ### end Alembic commands ###
