"""change proxy_number to 24 character

Revision ID: bcac4cd8a2c7
Revises: bec08c076fa6
Create Date: 2022-08-12 15:58:55.059024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bcac4cd8a2c7"
down_revision = "bec08c076fa6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
