"""Adding on delete cascade again

Revision ID: bd1270cf14a7
Revises: 194d5ec7da65
Create Date: 2022-09-06 05:15:46.805015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd1270cf14a7'
down_revision = '194d5ec7da65'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
