"""larger error message varchar

Revision ID: bd574c3ca474
Revises: 9a592f400f08
Create Date: 2022-08-16 18:27:34.797704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bd574c3ca474"
down_revision = "9a592f400f08"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
