"""change proxy to proxy_number

Revision ID: bec08c076fa6
Revises: c522de031f3b
Create Date: 2022-08-12 15:06:05.435947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bec08c076fa6'
down_revision = 'c522de031f3b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('proxy_number', sa.VARCHAR(length=12), nullable=True))
    op.drop_column('members', 'proxy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('proxy', sa.VARCHAR(length=11), autoincrement=False, nullable=True))
    op.drop_column('members', 'proxy_number')
    # ### end Alembic commands ###
