"""number names column

Revision ID: bf410860a9c4
Revises: 118c35db1b0d
Create Date: 2022-09-08 05:34:17.080059

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf410860a9c4'
down_revision = '118c35db1b0d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
