"""Adding relationships

Revision ID: c2016143aeff
Revises: bd1270cf14a7
Create Date: 2022-09-06 05:20:49.054994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2016143aeff'
down_revision = 'bd1270cf14a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
