"""change number to + notation

Revision ID: c522de031f3b
Revises: b1433729b1e5
Create Date: 2022-08-12 14:59:44.310216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c522de031f3b'
down_revision = 'b1433729b1e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
