"""number names column add

Revision ID: cfd14f4abf4b
Revises: 81873d5014f7
Create Date: 2022-09-08 05:35:33.726796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfd14f4abf4b'
down_revision = '81873d5014f7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
