"""number names column

Revision ID: d12582287774
Revises: 3cf54c1b6ece
Create Date: 2022-09-08 05:32:26.516956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd12582287774'
down_revision = '3cf54c1b6ece'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
