"""unique constraint on number and member, not name

Revision ID: d3ab0454dbb8
Revises: 0d57fa22b352
Create Date: 2022-08-17 14:34:56.339271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d3ab0454dbb8"
down_revision = "0d57fa22b352"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("contacts_name_number_member_id_key", "contacts", type_="unique")
    op.create_unique_constraint(None, "contacts", ["number", "member_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "contacts", type_="unique")
    op.create_unique_constraint(
        "contacts_name_number_member_id_key",
        "contacts",
        ["name", "number", "member_id"],
    )
    # ### end Alembic commands ###
