"""number names column

Revision ID: d3bd5548ce4c
Revises: 44deaa847e9e
Create Date: 2022-09-08 05:31:51.859446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3bd5548ce4c'
down_revision = '44deaa847e9e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('group_contacts', 'contact_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('group_contacts', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('groups', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('members', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('messages', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('members', 'email',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('groups', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('group_contacts', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('group_contacts', 'contact_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('contacts', 'member_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
