"""create member contacts

Revision ID: dda517000d94
Revises: 2b130f490b31
Create Date: 2022-08-12 11:23:40.845993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dda517000d94'
down_revision = '2b130f490b31'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_contacts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('member_id', sa.INTEGER(), nullable=True),
    sa.Column('contact_id', sa.INTEGER(), nullable=True),
    sa.Column('created_on', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('contacts_member_id_fkey', 'contacts', type_='foreignkey')
    op.drop_column('contacts', 'member_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('member_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('contacts_member_id_fkey', 'contacts', 'members', ['member_id'], ['id'])
    op.drop_table('member_contacts')
    # ### end Alembic commands ###
