"""maintenance

Revision ID: efccc07b6beb
Revises: 5f6d42fe9862
Create Date: 2022-08-24 19:03:39.603428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efccc07b6beb'
down_revision = '5f6d42fe9862'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_e')
    op.create_unique_constraint(None, 'group_contacts', ['contact_id', 'group_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group_contacts', type_='unique')
    op.create_table('t_e',
    sa.Column('docs', sa.TEXT(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
