"""Rename columns

Revision ID: f5ff289926db
Revises: e96d1ea78ab3
Create Date: 2022-09-08 06:26:18.966602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ff289926db'
down_revision = 'e96d1ea78ab3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
