"""unique constraint on contact name and member

Revision ID: f99870f12a9d
Revises: 13a5c0ab001d
Create Date: 2022-09-14 05:40:02.927514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99870f12a9d'
down_revision = '13a5c0ab001d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contacts_number_member_id_key', 'contacts', type_='unique')
    op.create_unique_constraint(None, 'contacts', ['name', 'member_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='unique')
    op.create_unique_constraint('contacts_number_member_id_key', 'contacts', ['number', 'member_id'])
    # ### end Alembic commands ###
