"""change phone_number name

Revision ID: f9d1f5e96111
Revises: 70accf65f508
Create Date: 2022-08-12 16:00:54.017679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d1f5e96111'
down_revision = '70accf65f508'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contacts', sa.Column('phone_number', sa.VARCHAR(length=12), nullable=True))
    op.drop_column('contacts', 'number')
    op.add_column('members', sa.Column('phone_number', sa.VARCHAR(length=12), nullable=True))
    op.drop_constraint('members_number_key', 'members', type_='unique')
    op.create_unique_constraint(None, 'members', ['phone_number'])
    op.drop_column('members', 'number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('number', sa.VARCHAR(length=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'members', type_='unique')
    op.create_unique_constraint('members_number_key', 'members', ['number'])
    op.drop_column('members', 'phone_number')
    op.add_column('contacts', sa.Column('number', sa.VARCHAR(length=11), autoincrement=False, nullable=True))
    op.drop_column('contacts', 'phone_number')
    # ### end Alembic commands ###
