"""number names column add integer new

Revision ID: f9d8a117756f
Revises: b2162ee18c97
Create Date: 2022-09-08 05:49:12.629825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9d8a117756f'
down_revision = 'b2162ee18c97'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'number_names')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('number_names', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
